### ISSUE TITLE
Name it!

### ISSUE THREAD

**Issue by paulwwisl** [susnigdha1/PlaywrightTestAutomationFramework#1]
The name Playwright within testing is likely owned legally by Microsoft.

Consider give this some other, unique name.

**Comment by susnigdha1** [comment]
I am using same Apache2 license, used by the original distribution of Playwright java package. In no capacity I am claiming any rights, part or full, on the Playwright tool and its original java distribution package, neither I am submitting a patent, nor I am trying to claim a copyright. Since I am using Playwright dependency to create this framewok, I have named it as "PlaywrightTestAutomationFramework", which is unique as per GitHub. So, I don't sense a problem here, however, I will check with Microsoft on this regard. Thank you for your time and feedback.

**Comment by paulwwisl** [comment]
well, I actually don't think about this issue as legal stuff,
is just when I would say "PlaywrightTestAutomationFramework" people would hear "Playwright Test Automation Framework"
and when they google the first link would be the Playwright itself, then some articles about it
like https://www.browserstack.com/guide/playwright-tutorial titles "Playwright Automation Framework: Tutorial"

So when you come with a name something new that is actually [name-of-base-framework]+[base-framework-genera-description], there is no any unique thing, other than say, it is on GitHub under  https://github.com/susnigdha1/
So susnigdha1 becomes identifying prefix.

**Comment by susnigdha1** [comment]
Thanks, closing it.
